
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  indexer:
    image: evm-indexer:latest
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "/evm-indexer"
    command: ['start', '-c', '/exemple.config.json', '-a', '/abis']
    container_name: indexer
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./docker/exemple.config.json:/exemple.config.json
      - ./datastore:/datastore
      - ./cmd/evm-indexer/abis:/abis:ro

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_DB: evmi_cloud
      CLICKHOUSE_PASSWORD: secret
    volumes:
      # Store data to HDD
      - ./clickhouse-data:/var/lib/clickhouse/
    ports:
      - "8123:8123/tcp"
      - "9000:9000/tcp"

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    environment:
      VITE_CLICKHOUSE_URL: http://localhost:8123
      VITE_CLICKHOUSE_USE_ADVANCED: 'true'
      VITE_CLICKHOUSE_USER: default
      VITE_CLICKHOUSE_PASS: secret
    ports:
      - "5521:5521/tcp"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
        
  grafana:
    image: grafana/grafana
    ports:
      - 30000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana