// Wire protocol between the EVMI server (host) and an exporter plugin
// (subprocess), spoken over hashicorp/go-plugin's gRPC transport.
//
// The Go types in pkg/exporter (Exporter, LogEvent, Context, ConfigField) are the
// author-facing API; these messages are their transport encoding. Keep the two in
// sync: adding a field to LogEvent means adding it here and in the client/server
// adapters (grpc_client.go / grpc_server.go).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: exporter.proto

package exporterproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExporterPluginService_Name_FullMethodName         = "/evmi.exporter.v1.ExporterPluginService/Name"
	ExporterPluginService_ConfigSchema_FullMethodName = "/evmi.exporter.v1.ExporterPluginService/ConfigSchema"
	ExporterPluginService_Init_FullMethodName         = "/evmi.exporter.v1.ExporterPluginService/Init"
	ExporterPluginService_NewLogEvent_FullMethodName  = "/evmi.exporter.v1.ExporterPluginService/NewLogEvent"
	ExporterPluginService_Close_FullMethodName        = "/evmi.exporter.v1.ExporterPluginService/Close"
)

// ExporterPluginServiceClient is the client API for ExporterPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExporterPluginService is served by the plugin process and called by the EVMI server.
// Calls are made strictly sequentially, in this order: ConfigSchema (install
// time only), Init, then NewLogEvent once per stored log in (block, log_index)
// order, then Close.
type ExporterPluginServiceClient interface {
	// Name returns the plugin's human-readable identifier.
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	// ConfigSchema returns the plugin's declared config parameters. Called once at
	// install time to record the schema on the Plugin row.
	ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
	// Init is called once before any NewLogEvent.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// NewLogEvent delivers one stored log.
	NewLogEvent(ctx context.Context, in *NewLogEventRequest, opts ...grpc.CallOption) (*NewLogEventResponse, error)
	// Close asks the plugin to flush and release resources. The host kills the
	// process afterwards.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type exporterPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExporterPluginServiceClient(cc grpc.ClientConnInterface) ExporterPluginServiceClient {
	return &exporterPluginServiceClient{cc}
}

func (c *exporterPluginServiceClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_ConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) NewLogEvent(ctx context.Context, in *NewLogEventRequest, opts ...grpc.CallOption) (*NewLogEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLogEventResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_NewLogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExporterPluginServiceServer is the server API for ExporterPluginService service.
// All implementations must embed UnimplementedExporterPluginServiceServer
// for forward compatibility.
//
// ExporterPluginService is served by the plugin process and called by the EVMI server.
// Calls are made strictly sequentially, in this order: ConfigSchema (install
// time only), Init, then NewLogEvent once per stored log in (block, log_index)
// order, then Close.
type ExporterPluginServiceServer interface {
	// Name returns the plugin's human-readable identifier.
	Name(context.Context, *NameRequest) (*NameResponse, error)
	// ConfigSchema returns the plugin's declared config parameters. Called once at
	// install time to record the schema on the Plugin row.
	ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error)
	// Init is called once before any NewLogEvent.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// NewLogEvent delivers one stored log.
	NewLogEvent(context.Context, *NewLogEventRequest) (*NewLogEventResponse, error)
	// Close asks the plugin to flush and release resources. The host kills the
	// process afterwards.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedExporterPluginServiceServer()
}

// UnimplementedExporterPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExporterPluginServiceServer struct{}

func (UnimplementedExporterPluginServiceServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedExporterPluginServiceServer) ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigSchema not implemented")
}
func (UnimplementedExporterPluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedExporterPluginServiceServer) NewLogEvent(context.Context, *NewLogEventRequest) (*NewLogEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewLogEvent not implemented")
}
func (UnimplementedExporterPluginServiceServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedExporterPluginServiceServer) mustEmbedUnimplementedExporterPluginServiceServer() {}
func (UnimplementedExporterPluginServiceServer) testEmbeddedByValue()                               {}

// UnsafeExporterPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExporterPluginServiceServer will
// result in compilation errors.
type UnsafeExporterPluginServiceServer interface {
	mustEmbedUnimplementedExporterPluginServiceServer()
}

func RegisterExporterPluginServiceServer(s grpc.ServiceRegistrar, srv ExporterPluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedExporterPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExporterPluginService_ServiceDesc, srv)
}

func _ExporterPluginService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_ConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).ConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_ConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).ConfigSchema(ctx, req.(*ConfigSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_NewLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewLogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).NewLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_NewLogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).NewLogEvent(ctx, req.(*NewLogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExporterPluginService_ServiceDesc is the grpc.ServiceDesc for ExporterPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExporterPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evmi.exporter.v1.ExporterPluginService",
	HandlerType: (*ExporterPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _ExporterPluginService_Name_Handler,
		},
		{
			MethodName: "ConfigSchema",
			Handler:    _ExporterPluginService_ConfigSchema_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ExporterPluginService_Init_Handler,
		},
		{
			MethodName: "NewLogEvent",
			Handler:    _ExporterPluginService_NewLogEvent_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _ExporterPluginService_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exporter.proto",
}

const (
	ExporterHostService_GetBlockchain_FullMethodName   = "/evmi.exporter.v1.ExporterHostService/GetBlockchain"
	ExporterHostService_CreateLogSource_FullMethodName = "/evmi.exporter.v1.ExporterHostService/CreateLogSource"
	ExporterHostService_UpsertAbi_FullMethodName       = "/evmi.exporter.v1.ExporterHostService/UpsertAbi"
	ExporterHostService_GetAbi_FullMethodName          = "/evmi.exporter.v1.ExporterHostService/GetAbi"
	ExporterHostService_ListAbis_FullMethodName        = "/evmi.exporter.v1.ExporterHostService/ListAbis"
)

// ExporterHostServiceClient is the client API for ExporterHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExporterHostService is served by the EVMI server on a go-plugin broker
// connection and called by the plugin process (the reverse direction of
// ExporterPluginService). It is scoped to the calling exporter: every call is
// answered in the context of that exporter's pipeline, and requests naming
// entities outside it are rejected.
type ExporterHostServiceClient interface {
	// GetBlockchain returns the chain the exporter's pipeline indexes, including
	// the JSON-RPC endpoint the indexer itself polls, so a plugin can open its own
	// client against the same node to fetch data the logs don't carry.
	GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error)
	// CreateLogSource registers a new log source as a child of an existing source
	// in the exporter's pipeline. It is idempotent per (parent, address).
	CreateLogSource(ctx context.Context, in *CreateLogSourceRequest, opts ...grpc.CallOption) (*CreateLogSourceResponse, error)
	// UpsertAbi creates an ABI if no ABI with that contract name exists, and
	// returns its id either way.
	UpsertAbi(ctx context.Context, in *UpsertAbiRequest, opts ...grpc.CallOption) (*UpsertAbiResponse, error)
	// GetAbi looks one ABI up by contract name or id.
	GetAbi(ctx context.Context, in *GetAbiRequest, opts ...grpc.CallOption) (*GetAbiResponse, error)
	// ListAbis returns every registered ABI.
	ListAbis(ctx context.Context, in *ListAbisRequest, opts ...grpc.CallOption) (*ListAbisResponse, error)
}

type exporterHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExporterHostServiceClient(cc grpc.ClientConnInterface) ExporterHostServiceClient {
	return &exporterHostServiceClient{cc}
}

func (c *exporterHostServiceClient) GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockchainResponse)
	err := c.cc.Invoke(ctx, ExporterHostService_GetBlockchain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterHostServiceClient) CreateLogSource(ctx context.Context, in *CreateLogSourceRequest, opts ...grpc.CallOption) (*CreateLogSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogSourceResponse)
	err := c.cc.Invoke(ctx, ExporterHostService_CreateLogSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterHostServiceClient) UpsertAbi(ctx context.Context, in *UpsertAbiRequest, opts ...grpc.CallOption) (*UpsertAbiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertAbiResponse)
	err := c.cc.Invoke(ctx, ExporterHostService_UpsertAbi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterHostServiceClient) GetAbi(ctx context.Context, in *GetAbiRequest, opts ...grpc.CallOption) (*GetAbiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbiResponse)
	err := c.cc.Invoke(ctx, ExporterHostService_GetAbi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterHostServiceClient) ListAbis(ctx context.Context, in *ListAbisRequest, opts ...grpc.CallOption) (*ListAbisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAbisResponse)
	err := c.cc.Invoke(ctx, ExporterHostService_ListAbis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExporterHostServiceServer is the server API for ExporterHostService service.
// All implementations must embed UnimplementedExporterHostServiceServer
// for forward compatibility.
//
// ExporterHostService is served by the EVMI server on a go-plugin broker
// connection and called by the plugin process (the reverse direction of
// ExporterPluginService). It is scoped to the calling exporter: every call is
// answered in the context of that exporter's pipeline, and requests naming
// entities outside it are rejected.
type ExporterHostServiceServer interface {
	// GetBlockchain returns the chain the exporter's pipeline indexes, including
	// the JSON-RPC endpoint the indexer itself polls, so a plugin can open its own
	// client against the same node to fetch data the logs don't carry.
	GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error)
	// CreateLogSource registers a new log source as a child of an existing source
	// in the exporter's pipeline. It is idempotent per (parent, address).
	CreateLogSource(context.Context, *CreateLogSourceRequest) (*CreateLogSourceResponse, error)
	// UpsertAbi creates an ABI if no ABI with that contract name exists, and
	// returns its id either way.
	UpsertAbi(context.Context, *UpsertAbiRequest) (*UpsertAbiResponse, error)
	// GetAbi looks one ABI up by contract name or id.
	GetAbi(context.Context, *GetAbiRequest) (*GetAbiResponse, error)
	// ListAbis returns every registered ABI.
	ListAbis(context.Context, *ListAbisRequest) (*ListAbisResponse, error)
	mustEmbedUnimplementedExporterHostServiceServer()
}

// UnimplementedExporterHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExporterHostServiceServer struct{}

func (UnimplementedExporterHostServiceServer) GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockchain not implemented")
}
func (UnimplementedExporterHostServiceServer) CreateLogSource(context.Context, *CreateLogSourceRequest) (*CreateLogSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLogSource not implemented")
}
func (UnimplementedExporterHostServiceServer) UpsertAbi(context.Context, *UpsertAbiRequest) (*UpsertAbiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAbi not implemented")
}
func (UnimplementedExporterHostServiceServer) GetAbi(context.Context, *GetAbiRequest) (*GetAbiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbi not implemented")
}
func (UnimplementedExporterHostServiceServer) ListAbis(context.Context, *ListAbisRequest) (*ListAbisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAbis not implemented")
}
func (UnimplementedExporterHostServiceServer) mustEmbedUnimplementedExporterHostServiceServer() {}
func (UnimplementedExporterHostServiceServer) testEmbeddedByValue()                             {}

// UnsafeExporterHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExporterHostServiceServer will
// result in compilation errors.
type UnsafeExporterHostServiceServer interface {
	mustEmbedUnimplementedExporterHostServiceServer()
}

func RegisterExporterHostServiceServer(s grpc.ServiceRegistrar, srv ExporterHostServiceServer) {
	// If the following call pancis, it indicates UnimplementedExporterHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExporterHostService_ServiceDesc, srv)
}

func _ExporterHostService_GetBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterHostServiceServer).GetBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterHostService_GetBlockchain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterHostServiceServer).GetBlockchain(ctx, req.(*GetBlockchainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterHostService_CreateLogSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterHostServiceServer).CreateLogSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterHostService_CreateLogSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterHostServiceServer).CreateLogSource(ctx, req.(*CreateLogSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterHostService_UpsertAbi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAbiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterHostServiceServer).UpsertAbi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterHostService_UpsertAbi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterHostServiceServer).UpsertAbi(ctx, req.(*UpsertAbiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterHostService_GetAbi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterHostServiceServer).GetAbi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterHostService_GetAbi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterHostServiceServer).GetAbi(ctx, req.(*GetAbiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterHostService_ListAbis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAbisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterHostServiceServer).ListAbis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterHostService_ListAbis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterHostServiceServer).ListAbis(ctx, req.(*ListAbisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExporterHostService_ServiceDesc is the grpc.ServiceDesc for ExporterHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExporterHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evmi.exporter.v1.ExporterHostService",
	HandlerType: (*ExporterHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockchain",
			Handler:    _ExporterHostService_GetBlockchain_Handler,
		},
		{
			MethodName: "CreateLogSource",
			Handler:    _ExporterHostService_CreateLogSource_Handler,
		},
		{
			MethodName: "UpsertAbi",
			Handler:    _ExporterHostService_UpsertAbi_Handler,
		},
		{
			MethodName: "GetAbi",
			Handler:    _ExporterHostService_GetAbi_Handler,
		},
		{
			MethodName: "ListAbis",
			Handler:    _ExporterHostService_ListAbis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exporter.proto",
}
