// Wire protocol between the EVMI server (host) and an exporter plugin
// (subprocess), spoken over hashicorp/go-plugin's gRPC transport.
//
// The Go types in pkg/exporter (Exporter, LogEvent, Context, ConfigField) are the
// author-facing API; these messages are their transport encoding. Keep the two in
// sync: adding a field to LogEvent means adding it here and in the client/server
// adapters (grpc_client.go / grpc_server.go).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: exporter.proto

package exporterproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExporterPluginService_Name_FullMethodName         = "/evmi.exporter.v1.ExporterPluginService/Name"
	ExporterPluginService_ConfigSchema_FullMethodName = "/evmi.exporter.v1.ExporterPluginService/ConfigSchema"
	ExporterPluginService_Init_FullMethodName         = "/evmi.exporter.v1.ExporterPluginService/Init"
	ExporterPluginService_NewLogEvent_FullMethodName  = "/evmi.exporter.v1.ExporterPluginService/NewLogEvent"
	ExporterPluginService_Close_FullMethodName        = "/evmi.exporter.v1.ExporterPluginService/Close"
)

// ExporterPluginServiceClient is the client API for ExporterPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExporterPluginService is served by the plugin process and called by the EVMI server.
// Calls are made strictly sequentially, in this order: ConfigSchema (install
// time only), Init, then NewLogEvent once per stored log in (block, log_index)
// order, then Close.
type ExporterPluginServiceClient interface {
	// Name returns the plugin's human-readable identifier.
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	// ConfigSchema returns the plugin's declared config parameters. Called once at
	// install time to record the schema on the Plugin row.
	ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
	// Init is called once before any NewLogEvent.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// NewLogEvent delivers one stored log.
	NewLogEvent(ctx context.Context, in *NewLogEventRequest, opts ...grpc.CallOption) (*NewLogEventResponse, error)
	// Close asks the plugin to flush and release resources. The host kills the
	// process afterwards.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type exporterPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExporterPluginServiceClient(cc grpc.ClientConnInterface) ExporterPluginServiceClient {
	return &exporterPluginServiceClient{cc}
}

func (c *exporterPluginServiceClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_ConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) NewLogEvent(ctx context.Context, in *NewLogEventRequest, opts ...grpc.CallOption) (*NewLogEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLogEventResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_NewLogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exporterPluginServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, ExporterPluginService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExporterPluginServiceServer is the server API for ExporterPluginService service.
// All implementations must embed UnimplementedExporterPluginServiceServer
// for forward compatibility.
//
// ExporterPluginService is served by the plugin process and called by the EVMI server.
// Calls are made strictly sequentially, in this order: ConfigSchema (install
// time only), Init, then NewLogEvent once per stored log in (block, log_index)
// order, then Close.
type ExporterPluginServiceServer interface {
	// Name returns the plugin's human-readable identifier.
	Name(context.Context, *NameRequest) (*NameResponse, error)
	// ConfigSchema returns the plugin's declared config parameters. Called once at
	// install time to record the schema on the Plugin row.
	ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error)
	// Init is called once before any NewLogEvent.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// NewLogEvent delivers one stored log.
	NewLogEvent(context.Context, *NewLogEventRequest) (*NewLogEventResponse, error)
	// Close asks the plugin to flush and release resources. The host kills the
	// process afterwards.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedExporterPluginServiceServer()
}

// UnimplementedExporterPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExporterPluginServiceServer struct{}

func (UnimplementedExporterPluginServiceServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedExporterPluginServiceServer) ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigSchema not implemented")
}
func (UnimplementedExporterPluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedExporterPluginServiceServer) NewLogEvent(context.Context, *NewLogEventRequest) (*NewLogEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewLogEvent not implemented")
}
func (UnimplementedExporterPluginServiceServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedExporterPluginServiceServer) mustEmbedUnimplementedExporterPluginServiceServer() {}
func (UnimplementedExporterPluginServiceServer) testEmbeddedByValue()                               {}

// UnsafeExporterPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExporterPluginServiceServer will
// result in compilation errors.
type UnsafeExporterPluginServiceServer interface {
	mustEmbedUnimplementedExporterPluginServiceServer()
}

func RegisterExporterPluginServiceServer(s grpc.ServiceRegistrar, srv ExporterPluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedExporterPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExporterPluginService_ServiceDesc, srv)
}

func _ExporterPluginService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_ConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).ConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_ConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).ConfigSchema(ctx, req.(*ConfigSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_NewLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewLogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).NewLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_NewLogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).NewLogEvent(ctx, req.(*NewLogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExporterPluginService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExporterPluginServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExporterPluginService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExporterPluginServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExporterPluginService_ServiceDesc is the grpc.ServiceDesc for ExporterPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExporterPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evmi.exporter.v1.ExporterPluginService",
	HandlerType: (*ExporterPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _ExporterPluginService_Name_Handler,
		},
		{
			MethodName: "ConfigSchema",
			Handler:    _ExporterPluginService_ConfigSchema_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ExporterPluginService_Init_Handler,
		},
		{
			MethodName: "NewLogEvent",
			Handler:    _ExporterPluginService_NewLogEvent_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _ExporterPluginService_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exporter.proto",
}
