apiVersion: v1
kind: Service
metadata:
  name: {{ include "evmi.fullname" . }}-gateway
  labels:
    {{- include "evmi.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "evmi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
