package gateway

// Code generated by handlers generator; do NOT edit by hand.
// Each method resolves the backend that owns the addressed data, then forwards
// the (message + auth) to it. Shared metadata RPCs go to any RUNNING instance.
// InstallPlugin is intentionally absent — it is fanned out in gateway.go.

import (
	"context"

	"connectrpc.com/connect"

	v1 "github.com/evmi-cloud/go-evm-indexer/internal/grpc/generated/evm_indexer/v1"
)

// ---- shared metadata (routed to any RUNNING instance) ----

// GetEvmiInstance — shared metadata DB; any instance
func (g *Gateway) GetEvmiInstance(ctx context.Context, req *connect.Request[v1.GetEvmiInstanceRequest]) (*connect.Response[v1.GetEvmiInstanceResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmiInstance)
}

// ListEvmiInstances — shared metadata DB; any instance
func (g *Gateway) ListEvmiInstances(ctx context.Context, req *connect.Request[v1.ListEvmiInstancesRequest]) (*connect.Response[v1.ListEvmiInstancesResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmiInstances)
}

// CreateEvmBlockchain — shared metadata DB; any instance
func (g *Gateway) CreateEvmBlockchain(ctx context.Context, req *connect.Request[v1.CreateEvmBlockchainRequest]) (*connect.Response[v1.CreateEvmBlockchainResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmBlockchain)
}

// GetEvmBlockchain — shared metadata DB; any instance
func (g *Gateway) GetEvmBlockchain(ctx context.Context, req *connect.Request[v1.GetEvmBlockchainRequest]) (*connect.Response[v1.GetEvmBlockchainResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmBlockchain)
}

// UpdateEvmBlockchain — shared metadata DB; any instance
func (g *Gateway) UpdateEvmBlockchain(ctx context.Context, req *connect.Request[v1.UpdateEvmBlockchainRequest]) (*connect.Response[v1.UpdateEvmBlockchainResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmBlockchain)
}

// ListEvmBlockchains — shared metadata DB; any instance
func (g *Gateway) ListEvmBlockchains(ctx context.Context, req *connect.Request[v1.ListEvmBlockchainsRequest]) (*connect.Response[v1.ListEvmBlockchainsResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmBlockchains)
}

// DeleteEvmBlockchain — shared metadata DB; any instance
func (g *Gateway) DeleteEvmBlockchain(ctx context.Context, req *connect.Request[v1.DeleteEvmBlockchainRequest]) (*connect.Response[v1.DeleteEvmBlockchainResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmBlockchain)
}

// CreateEvmJsonAbi — shared metadata DB; any instance
func (g *Gateway) CreateEvmJsonAbi(ctx context.Context, req *connect.Request[v1.CreateEvmJsonAbiRequest]) (*connect.Response[v1.CreateEvmJsonAbiResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmJsonAbi)
}

// GetEvmJsonAbi — shared metadata DB; any instance
func (g *Gateway) GetEvmJsonAbi(ctx context.Context, req *connect.Request[v1.GetEvmJsonAbiRequest]) (*connect.Response[v1.GetEvmJsonAbiResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmJsonAbi)
}

// UpdateEvmJsonAbi — shared metadata DB; any instance
func (g *Gateway) UpdateEvmJsonAbi(ctx context.Context, req *connect.Request[v1.UpdateEvmJsonAbiRequest]) (*connect.Response[v1.UpdateEvmJsonAbiResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmJsonAbi)
}

// ListEvmJsonAbis — shared metadata DB; any instance
func (g *Gateway) ListEvmJsonAbis(ctx context.Context, req *connect.Request[v1.ListEvmJsonAbisRequest]) (*connect.Response[v1.ListEvmJsonAbisResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmJsonAbis)
}

// DeleteEvmJsonAbi — shared metadata DB; any instance
func (g *Gateway) DeleteEvmJsonAbi(ctx context.Context, req *connect.Request[v1.DeleteEvmJsonAbiRequest]) (*connect.Response[v1.DeleteEvmJsonAbiResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmJsonAbi)
}

// CreateEvmLogStore — shared metadata DB; any instance
func (g *Gateway) CreateEvmLogStore(ctx context.Context, req *connect.Request[v1.CreateEvmLogStoreRequest]) (*connect.Response[v1.CreateEvmLogStoreResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmLogStore)
}

// GetEvmLogStore — shared metadata DB; any instance
func (g *Gateway) GetEvmLogStore(ctx context.Context, req *connect.Request[v1.GetEvmLogStoreRequest]) (*connect.Response[v1.GetEvmLogStoreResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmLogStore)
}

// UpdateEvmLogStore — shared metadata DB; any instance
func (g *Gateway) UpdateEvmLogStore(ctx context.Context, req *connect.Request[v1.UpdateEvmLogStoreRequest]) (*connect.Response[v1.UpdateEvmLogStoreResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmLogStore)
}

// ListEvmLogStores — shared metadata DB; any instance
func (g *Gateway) ListEvmLogStores(ctx context.Context, req *connect.Request[v1.ListEvmLogStoresRequest]) (*connect.Response[v1.ListEvmLogStoresResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmLogStores)
}

// DeleteEvmLogStore — shared metadata DB; any instance
func (g *Gateway) DeleteEvmLogStore(ctx context.Context, req *connect.Request[v1.DeleteEvmLogStoreRequest]) (*connect.Response[v1.DeleteEvmLogStoreResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmLogStore)
}

// ListEvmLogPipelines — shared metadata DB; any instance
func (g *Gateway) ListEvmLogPipelines(ctx context.Context, req *connect.Request[v1.ListEvmLogPipelinesRequest]) (*connect.Response[v1.ListEvmLogPipelinesResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmLogPipelines)
}

// ListEvmLogSources — shared metadata DB; any instance
func (g *Gateway) ListEvmLogSources(ctx context.Context, req *connect.Request[v1.ListEvmLogSourcesRequest]) (*connect.Response[v1.ListEvmLogSourcesResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmLogSources)
}

// ListEvmiExporters — shared metadata DB; any instance
func (g *Gateway) ListEvmiExporters(ctx context.Context, req *connect.Request[v1.ListEvmiExportersRequest]) (*connect.Response[v1.ListEvmiExportersResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmiExporters)
}

// Login — shared metadata DB; any instance
func (g *Gateway) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.Login)
}

// ListOAuthLoginUrls — shared metadata DB; any instance
func (g *Gateway) ListOAuthLoginUrls(ctx context.Context, req *connect.Request[v1.ListOAuthLoginUrlsRequest]) (*connect.Response[v1.ListOAuthLoginUrlsResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListOAuthLoginUrls)
}

// Me — shared metadata DB; any instance
func (g *Gateway) Me(ctx context.Context, req *connect.Request[v1.MeRequest]) (*connect.Response[v1.MeResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.Me)
}

// CreateAccessToken — shared metadata DB; any instance
func (g *Gateway) CreateAccessToken(ctx context.Context, req *connect.Request[v1.CreateAccessTokenRequest]) (*connect.Response[v1.CreateAccessTokenResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateAccessToken)
}

// ListAccessTokens — shared metadata DB; any instance
func (g *Gateway) ListAccessTokens(ctx context.Context, req *connect.Request[v1.ListAccessTokensRequest]) (*connect.Response[v1.ListAccessTokensResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListAccessTokens)
}

// RevokeAccessToken — shared metadata DB; any instance
func (g *Gateway) RevokeAccessToken(ctx context.Context, req *connect.Request[v1.RevokeAccessTokenRequest]) (*connect.Response[v1.RevokeAccessTokenResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.RevokeAccessToken)
}

// ListOAuthProviders — shared metadata DB; any instance
func (g *Gateway) ListOAuthProviders(ctx context.Context, req *connect.Request[v1.ListOAuthProvidersRequest]) (*connect.Response[v1.ListOAuthProvidersResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListOAuthProviders)
}

// CreateOAuthProvider — shared metadata DB; any instance
func (g *Gateway) CreateOAuthProvider(ctx context.Context, req *connect.Request[v1.CreateOAuthProviderRequest]) (*connect.Response[v1.CreateOAuthProviderResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateOAuthProvider)
}

// UpdateOAuthProvider — shared metadata DB; any instance
func (g *Gateway) UpdateOAuthProvider(ctx context.Context, req *connect.Request[v1.UpdateOAuthProviderRequest]) (*connect.Response[v1.UpdateOAuthProviderResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateOAuthProvider)
}

// DeleteOAuthProvider — shared metadata DB; any instance
func (g *Gateway) DeleteOAuthProvider(ctx context.Context, req *connect.Request[v1.DeleteOAuthProviderRequest]) (*connect.Response[v1.DeleteOAuthProviderResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteOAuthProvider)
}

// ListUsers — shared metadata DB; any instance
func (g *Gateway) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListUsers)
}

// CreateUser — shared metadata DB; any instance
func (g *Gateway) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateUser)
}

// UpdateUser — shared metadata DB; any instance
func (g *Gateway) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateUser)
}

// DeleteUser — shared metadata DB; any instance
func (g *Gateway) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteUser)
}

// CreatePlugin — shared metadata DB; any instance
func (g *Gateway) CreatePlugin(ctx context.Context, req *connect.Request[v1.CreatePluginRequest]) (*connect.Response[v1.CreatePluginResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreatePlugin)
}

// GetPlugin — shared metadata DB; any instance
func (g *Gateway) GetPlugin(ctx context.Context, req *connect.Request[v1.GetPluginRequest]) (*connect.Response[v1.GetPluginResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetPlugin)
}

// UpdatePlugin — shared metadata DB; any instance
func (g *Gateway) UpdatePlugin(ctx context.Context, req *connect.Request[v1.UpdatePluginRequest]) (*connect.Response[v1.UpdatePluginResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdatePlugin)
}

// ListPlugins — shared metadata DB; any instance
func (g *Gateway) ListPlugins(ctx context.Context, req *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListPlugins)
}

// DeletePlugin — shared metadata DB; any instance
func (g *Gateway) DeletePlugin(ctx context.Context, req *connect.Request[v1.DeletePluginRequest]) (*connect.Response[v1.DeletePluginResponse], error) {
	c, err := g.anyClient()
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeletePlugin)
}

// ---- data / control (routed to the owning instance) ----

// CreateEvmLogPipeline — owning instance
func (g *Gateway) CreateEvmLogPipeline(ctx context.Context, req *connect.Request[v1.CreateEvmLogPipelineRequest]) (*connect.Response[v1.CreateEvmLogPipelineResponse], error) {
	c, err := g.clientForInstance(uint(req.Msg.GetPipeline().GetEvmiInstanceId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmLogPipeline)
}

// GetEvmLogPipeline — owning instance
func (g *Gateway) GetEvmLogPipeline(ctx context.Context, req *connect.Request[v1.GetEvmLogPipelineRequest]) (*connect.Response[v1.GetEvmLogPipelineResponse], error) {
	c, err := g.clientForPipeline(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmLogPipeline)
}

// UpdateEvmLogPipeline — owning instance
func (g *Gateway) UpdateEvmLogPipeline(ctx context.Context, req *connect.Request[v1.UpdateEvmLogPipelineRequest]) (*connect.Response[v1.UpdateEvmLogPipelineResponse], error) {
	c, err := g.clientForPipeline(uint(req.Msg.GetPipeline().GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmLogPipeline)
}

// DeleteEvmLogPipeline — owning instance
func (g *Gateway) DeleteEvmLogPipeline(ctx context.Context, req *connect.Request[v1.DeleteEvmLogPipelineRequest]) (*connect.Response[v1.DeleteEvmLogPipelineResponse], error) {
	c, err := g.clientForPipeline(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmLogPipeline)
}

// StartSourceIndexer — owning instance
func (g *Gateway) StartSourceIndexer(ctx context.Context, req *connect.Request[v1.StartSourceIndexerRequest]) (*connect.Response[v1.StartSourceIndexerResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.StartSourceIndexer)
}

// StopSourceIndexer — owning instance
func (g *Gateway) StopSourceIndexer(ctx context.Context, req *connect.Request[v1.StopSourceIndexerRequest]) (*connect.Response[v1.StopSourceIndexerResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.StopSourceIndexer)
}

// CreateEvmLogSource — owning instance
func (g *Gateway) CreateEvmLogSource(ctx context.Context, req *connect.Request[v1.CreateEvmLogSourceRequest]) (*connect.Response[v1.CreateEvmLogSourceResponse], error) {
	c, err := g.clientForPipeline(uint(req.Msg.GetSource().GetEvmLogPipelineId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmLogSource)
}

// GetEvmLogSource — owning instance
func (g *Gateway) GetEvmLogSource(ctx context.Context, req *connect.Request[v1.GetEvmLogSourceRequest]) (*connect.Response[v1.GetEvmLogSourceResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmLogSource)
}

// UpdateEvmLogSource — owning instance
func (g *Gateway) UpdateEvmLogSource(ctx context.Context, req *connect.Request[v1.UpdateEvmLogSourceRequest]) (*connect.Response[v1.UpdateEvmLogSourceResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetSource().GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmLogSource)
}

// DeleteEvmLogSource — owning instance
func (g *Gateway) DeleteEvmLogSource(ctx context.Context, req *connect.Request[v1.DeleteEvmLogSourceRequest]) (*connect.Response[v1.DeleteEvmLogSourceResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmLogSource)
}

// ListEvmLogs — owning instance
func (g *Gateway) ListEvmLogs(ctx context.Context, req *connect.Request[v1.ListEvmLogsRequest]) (*connect.Response[v1.ListEvmLogsResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetSourceId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmLogs)
}

// ListLatestEvmLogs — owning instance
func (g *Gateway) ListLatestEvmLogs(ctx context.Context, req *connect.Request[v1.ListLatestEvmLogsRequest]) (*connect.Response[v1.ListLatestEvmLogsResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetSourceId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListLatestEvmLogs)
}

// ListEvmTransactions — owning instance
func (g *Gateway) ListEvmTransactions(ctx context.Context, req *connect.Request[v1.ListEvmTransactionsRequest]) (*connect.Response[v1.ListEvmTransactionsResponse], error) {
	c, err := g.clientForSource(uint(req.Msg.GetSourceId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.ListEvmTransactions)
}

// CreateEvmiExporter — owning instance
func (g *Gateway) CreateEvmiExporter(ctx context.Context, req *connect.Request[v1.CreateEvmiExporterRequest]) (*connect.Response[v1.CreateEvmiExporterResponse], error) {
	c, err := g.clientForPipeline(uint(req.Msg.GetExporter().GetEvmLogPipelineId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.CreateEvmiExporter)
}

// GetEvmiExporter — owning instance
func (g *Gateway) GetEvmiExporter(ctx context.Context, req *connect.Request[v1.GetEvmiExporterRequest]) (*connect.Response[v1.GetEvmiExporterResponse], error) {
	c, err := g.clientForExporter(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.GetEvmiExporter)
}

// UpdateEvmiExporter — owning instance
func (g *Gateway) UpdateEvmiExporter(ctx context.Context, req *connect.Request[v1.UpdateEvmiExporterRequest]) (*connect.Response[v1.UpdateEvmiExporterResponse], error) {
	c, err := g.clientForExporter(uint(req.Msg.GetExporter().GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.UpdateEvmiExporter)
}

// DeleteEvmiExporter — owning instance
func (g *Gateway) DeleteEvmiExporter(ctx context.Context, req *connect.Request[v1.DeleteEvmiExporterRequest]) (*connect.Response[v1.DeleteEvmiExporterResponse], error) {
	c, err := g.clientForExporter(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.DeleteEvmiExporter)
}

// StartExporter — owning instance
func (g *Gateway) StartExporter(ctx context.Context, req *connect.Request[v1.StartExporterRequest]) (*connect.Response[v1.StartExporterResponse], error) {
	c, err := g.clientForExporter(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.StartExporter)
}

// StopExporter — owning instance
func (g *Gateway) StopExporter(ctx context.Context, req *connect.Request[v1.StopExporterRequest]) (*connect.Response[v1.StopExporterResponse], error) {
	c, err := g.clientForExporter(uint(req.Msg.GetId()))
	if err != nil {
		return nil, err
	}
	return forward(ctx, req, c.StopExporter)
}
